### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by CalebCDE**
I need test it for check every string but atm is good i think.

### CODE REVIEW

**Comment by rootkiwi** [comment]
Thanks looks good.

But `res/values/strings.xml` should not be deleted, which is the default strings.
That should be left as is.

Instead a new folder should be created with the new spanish strings as such:
`res/values-es/strings.xml`

Info: https://developer.android.com/guide/topics/resources/localization.html

**Comment by CalebCDE** [comment]
Oki, then need crate a values-es folder? How can i can build that folder? (Newbie in github!) :)

**Comment by rootkiwi** [comment]
Yes you need to update your repository to include the updated english strings so it's the same as my repository, then create a values-es folder and put your strings in that folder named strings.xml.

Then commit to your repository then this pull request will update automatically.

I'm also kind of new to git, but I guess I can do a pullrequest to your repository if you feel that would be easier. Not sure exactly how that will work but I think that you should still get the credit for the commit.

**Comment by rootkiwi** [comment]
Thanks, merged with #13

**Pull request closed without merging**
